java/pracadomowa/zaj6
HubertKarw/zajecia pull request #2
Opened 2024-11-13 19:16 UTC by HubertKarw

2024-11-15 19:58 UTC, kkpolak requested changes

2024-11-15 19:58 UTC, kkpolak commented on zajecia/src/zajecia6/zadanie1.java
> +public class zadanie1 {
formatowanie

2024-11-15 19:58 UTC, kkpolak commented on zajecia/src/zajecia6/zadanie2.java
> +        int n =10;
do wczytania n powinnismy uzywac System.in i zmiennej do ktorej wczytamy

2024-11-15 19:58 UTC, kkpolak commented on zajecia/src/zajecia6/zadanie3.java
> +        int number = 1;
liczba powinna byc podawana przez uzytkownika

2024-11-15 19:58 UTC, kkpolak commented on zajecia/src/zajecia6/zadanie3.java
> +        for(int i=0;i<10;i++){
tabliczka mnozenia od 1 do 10, u Ciebie jest od do 9

2024-11-15 19:58 UTC, kkpolak commented on zajecia/src/zajecia6/zadanie8.java
> +public class zadanie8 {
calkiem spoko, ale powinnismy wczytywac char a nie int i sprawdzac czy jest to '+' '-' '*' '%' '/' i oczywscie jakis znak do wyjscia (tu dowolnie wedlug inwencji tworczej) warto tez dodac jakis default dla wszelkiego rodzaju innych znakow

2024-11-15 19:58 UTC, kkpolak commented on zajecia/src/zajecia6/zadanie15.java
> +import java.sql.SQLOutput;
ten import jest potrzebny?

2024-11-15 20:03 UTC, HubertKarw commented on zajecia/src/zajecia6/zadanie15.java
> +import java.sql.SQLOutput;
Import mi sie chyba zrobił jak souta z caps lockiem wpisałem

2024-11-27 20:47 UTC, kkpolak approved these changes

2024-11-28 18:31 UTC, merged